apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rhua
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rhua
    app.kubernetes.io/part-of: tkwch-fix-0075-0003-app
  name: devfile-sample-rhua
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rhua
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rhua
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0003-tenant/tkwch-fix-0075-0003-app/devfile-sample-rhua@sha256:3147d0e00d01a5214a0ac103d5f3949e63f4535c5364fa8d919c2fd253f3dbc5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
